name: Build and Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create env file
        run: |
          echo "SUPABASE_CLIENT_ANON_KEY=${{ secrets.SUPABASE_CLIENT_ANON_KEY }}" > .env

      - name: Build site
        run: |
          bundle install
          bundle exec jekyll build
        env:
          SUPABASE_CLIENT_ANON_KEY: ${{ secrets.SUPABASE_CLIENT_ANON_KEY }}