name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Debug Environment
      run: |
        echo "Checking environment setup..."
        echo "SUPABASE_KEY exists: ${{ env.SUPABASE_CLIENT_ANON_KEY != '' }}"
        echo "Jekyll env: $JEKYLL_ENV"
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: Install Dependencies
      run: |
        bundle install
    
    - name: Build Site
      env:
        SUPABASE_CLIENT_ANON_KEY: ${{ secrets.SUPABASE_CLIENT_ANON_KEY }}
      run: |
        echo "Building with environment variables..."
        env | grep SUPABASE || echo "No Supabase env found"
        JEKYLL_ENV=production bundle exec jekyll build --verbose
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site