name: Build and Deploy

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Debug Environment
      run: |
        echo "Testing secret access..."
        echo "Secret exists: ${{ secrets.SUPABASE_CLIENT_ANON_KEY != '' }}"
        if [ -n "${{ secrets.SUPABASE_CLIENT_ANON_KEY }}" ]; then
          echo "Secret is set"
        else
          echo "Secret is NOT set"
        fi
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: Create .env file
      run: |
        echo "SUPABASE_CLIENT_ANON_KEY=${{ secrets.SUPABASE_CLIENT_ANON_KEY }}" > .env

    - name: Build Site
      env:
        JEKYLL_ENV: production
        SUPABASE_CLIENT_ANON_KEY: ${{ secrets.SUPABASE_CLIENT_ANON_KEY }}
      run: |
        echo "Environment check:"
        if [ -n "$SUPABASE_CLIENT_ANON_KEY" ]; then
          echo "SUPABASE_CLIENT_ANON_KEY is set"
          bundle exec jekyll build --verbose
        else
          echo "Error: SUPABASE_CLIENT_ANON_KEY is not set"
          exit 1
        fi
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public